<?php
/** op-unit-translate:/ms-language.phtml
 *
 * @created    2023-03-26
 * @version    1.0
 * @package    op-unit-translate
 * @author     Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright  Tomoaki Nagahara All right reserved.
 */

 /** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP\UNIT\Translate;

/* @var $args array */
$json = $args['json'];

?>
<section class="translate language list">
    <ul>
        <?php foreach($json as $code => $lang): ?>
        <li class="<?= $lang['dir'] ?>" data-lang="<?= $code ?>"><?= $lang['nativeName'] ?></li>
        <?php endforeach; ?>
    </ul>
</section>
<?php
//D($json);
